spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/homer
    username: postgres
    password: homer_forever
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    properties:
      hibernate:
        default-schema: homer
        #        format_sql: true
        use_sql_comments: true
        session_factory:
          statement_inspector: com.example.demo.sqltracker.StatementInspectorImpl
        generate_statistics: true
#        batch_fetch_style: DYNAMIC
    hibernate:
      ddl-auto: create
#    show-sql: true