insert into users (id, first_name) values (1, 'John');
insert into address (id, street, user_id) values (1, 'Empty street', 1);
insert into address (id, street, user_id) values (2, 'Full street', 1);
insert into address (id, street, user_id) values (3, 'New street', 1);
insert into address (id, street, user_id) values (4, 'New street', 1);
insert into address (id, street, user_id) values (5, 'New street', 1);
insert into address (id, street, user_id) values (6, 'New street', 1);

insert into users (id, first_name) values (2, 'Alex2');
insert into users (id, first_name) values (3, 'Alex3');
insert into users (id, first_name) values (4, 'Alex4');
insert into users (id, first_name) values (5, 'Alex5');
insert into users (id, first_name) values (6, 'Alex6');
insert into users (id, first_name) values (7, 'Alex7');
insert into users (id, first_name) values (8, 'Alex8');
insert into users (id, first_name) values (9, 'Alex9');
insert into users (id, first_name) values (10, 'Alex10');
insert into users (id, first_name) values (11, 'Alex11');
insert into users (id, first_name) values (12, 'Alex12');
insert into users (id, first_name) values (13, 'Alex13');
insert into users (id, first_name) values (14, 'Alex14');
insert into users (id, first_name) values (15, 'Alex15');
insert into users (id, first_name) values (16, 'Alex16');
insert into users (id, first_name) values (17, 'Alex17');
insert into users (id, first_name) values (18, 'Alex18');
insert into users (id, first_name) values (19, 'Alex19');
insert into users (id, first_name) values (20, 'Alex20');
insert into users (id, first_name) values (21, 'Alex21');
insert into users (id, first_name) values (22, 'Alex22');
insert into users (id, first_name) values (23, 'Alex23');
insert into users (id, first_name) values (24, 'Alex24');
insert into users (id, first_name) values (25, 'Alex25');
insert into users (id, first_name) values (26, 'Alex26');
insert into users (id, first_name) values (27, 'Alex27');
insert into users (id, first_name) values (28, 'Alex28');
insert into users (id, first_name) values (29, 'Alex29');
insert into users (id, first_name) values (30, 'Alex30');
insert into users (id, first_name) values (31, 'Alex31');
insert into address (id, street, user_id) values (7, 'Empty street', 2);
insert into address (id, street, user_id) values (8, 'Full street', 3);
insert into address (id, street, user_id) values (9, 'New street', 4);
insert into address (id, street, user_id) values (10, 'New street', 5);
insert into address (id, street, user_id) values (11, 'New street', 6);
insert into address (id, street, user_id) values (12, 'New street', 7);
insert into address (id, street, user_id) values (13, 'Empty street', 8);
insert into address (id, street, user_id) values (14, 'Full street', 9);
insert into address (id, street, user_id) values (15, 'New street', 10);
insert into address (id, street, user_id) values (16, 'New street', 11);
insert into address (id, street, user_id) values (17, 'New street', 12);
insert into address (id, street, user_id) values (18, 'New street', 13);
insert into address (id, street, user_id) values (19, 'New street', 14);
insert into address (id, street, user_id) values (20, 'New street', 15);
insert into address (id, street, user_id) values (21, 'Empty street', 16);
insert into address (id, street, user_id) values (22, 'Full street', 17);
insert into address (id, street, user_id) values (23, 'New street', 18);
insert into address (id, street, user_id) values (24, 'New street', 19);
insert into address (id, street, user_id) values (25, 'New street', 20);
insert into address (id, street, user_id) values (26, 'New street', 21);
insert into address (id, street, user_id) values (27, 'New street', 22);
insert into address (id, street, user_id) values (28, 'New street', 23);
insert into address (id, street, user_id) values (29, 'New street', 24);
insert into address (id, street, user_id) values (30, 'New street', 25);
insert into address (id, street, user_id) values (31, 'New street', 26);
insert into address (id, street, user_id) values (32, 'New street', 27);
insert into address (id, street, user_id) values (33, 'New street', 28);
insert into address (id, street, user_id) values (34, 'New street', 29);
insert into address (id, street, user_id) values (35, 'New street', 30);
insert into address (id, street, user_id) values (36, 'New street', 31);